#!/bin/sh
# read our configuration
source /boot/config/plugins/unraid6-rtorrent/unraid6-rtorrent.cfg

# no-op if already running
if [ ! "$(pidof rtorrent)" ] ; then

	# if directory structure doesn't exist, create it
	if [ ! -e "$DATADIR/torrents" ]; then
		mkdir -p $DATADIR/torrents
	fi

	if [ ! -e "$DATADIR/torrent-metadata" ]; then
		mkdir -p $DATADIR/torrent-metadata
	fi


	# update the rtorrent.rc file with the plugin options
	/usr/local/emhttp/plugins/unraid6-rtorrent/scripts/update


	# removing locked rtorrent from session in case of previous bad reboot
	if [ -e "$DATADIR/torrent-metadata/rtorrent.lock" ]; then
		rm -f $DATADIR/torrent-metadata/rtorrent.lock
	fi

	screen -T linux -dmUS rtorrent rtorrent -n -o import=/boot/config/plugins/unraid6-rtorrent/rtorrent.rc
fi
