#!/bin/sh
# read our configuration
source /boot/config/plugins/unraid6-rtorrent/unraid6-rtorrent.cfg

# read unRaid variables
source /usr/local/emhttp/state/var.ini


# bind to the current unRaid host IP Address in rtorrent.rc
sed -i 's/^bind =.*/bind = '"$IPADDR"'/' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc 


# update directories in rtorrent.rc


# update UDP trackers in rtorrent.rc
case $UDPTRACKERS in
	enable* )
		sed -i 's/^use_udp_trackers =.*/use_udp_trackers = yes/' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc ;;
	* )
		sed -i 's/^use_udp_trackers =.*/use_udp_trackers = no/' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc ;;
esac


# update DHT in rtorrent.rc
case $DHT in
	enable* )
		sed -i 's/^dht =.*/dht = on/' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc ;;
	auto* )
		sed -i 's/^dht =.*/dht = auto/' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc ;;
	off* )
		sed -i 's/^dht =.*/dht = off/' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc ;;
	* )
		sed -i 's/^dht =.*/dht = disable/' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc ;;
esac


# update Peer Exchange in rtorrent.rc
case $PEXCHANGE in
	enable* )
		sed 's/^peer_exchange =.*/peer_exchange = yes/' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc ;;
	* )
		sed 's/^peer_exchange =.*/peer_exchange = no/' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc ;;
esac


# update XMLRPC support in rtorrent.rc
case $XMLRPC in
	enable* )
		# remove comment from scgi_port command
		sed -i '/scgi_port/ s/^# //' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc 
		
		# bind SCGI to port 5000 of the current unRaid host IP Address
		sed -i 's/^scgi_port =.*/scgi_port = '"$IPADDR"':5000/' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc 
		;;
    *)
		# comment out the scgi_port command
		sed -i '/^scgi_port/ s/^/# /' /boot/config/plugins/unraid6-rtorrent/rtorrent.rc ;;
esac
